package com.bottlevault.common.model

enum class AlcoholType {
    WHISKEY, BOURBON, SCOTCH, RYE, VODKA, GIN, RUM, TEQUILA, BRANDY, COGNAC,
    WINE_RED, WINE_WHITE, WINE_ROSE, WINE_SPARKLING, WINE_DESSERT,
    BEER, IPA, STOUT, LAGER, PILSNER, WHEAT_BEER,
    LIQUEUR, AMARO, VERMOUTH, ABSINTHE, MEZCAL, SAKE, OTHER
}
